runtime: python39

handlers:
- url: /style.css
  static_files: style.css
  upload: style.css

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: index.html
  upload: index.html
