import type { TaskDifficulty, TaskImpact, TaskPriority } from "@/generated/prisma/enums";
import type { Stage } from "@/lib/utils";

export type InstructionFieldType = "short_text" | "long_text";

export interface InstructionField {
  key: string;
  label: string;
  prompt: string;
  type: InstructionFieldType;
}

export interface TaskTemplateSeed {
  stage: Stage;
  category: string;
  title: string;
  whyItMatters: string;
  thinkPrompt: string;
  instructions: InstructionField[];
  implementGuidance: string;
  measurePrompt: string;
  difficulty: TaskDifficulty;
  impact: TaskImpact;
  priority: TaskPriority;
  estimatedMins: number;
  /** My Blueprint section this task's answers populate — see docs/BUILD_STATUS.md for the full section map. */
  blueprintDestination: string;
  /** Titles of other templates in this list that must be COMPLETED first. */
  prerequisiteTitles: string[];
  order: number;
}

const step = (
  key: string,
  label: string,
  prompt: string,
  type: InstructionFieldType = "long_text",
): InstructionField => ({ key, label, prompt, type });

/**
 * The Blueprint Business Builder task library (spec INITIAL TASK
 * LIBRARY): 30 tasks — 9 Passion, 12 Power, 9 Legacy — each following
 * the LEARN → THINK → BUILD → SAVE → IMPLEMENT → MEASURE structure:
 * whyItMatters (LEARN), thinkPrompt (THINK), instructions (BUILD steps,
 * saved via SAVE), implementGuidance (IMPLEMENT), measurePrompt
 * (MEASURE). Dependencies (spec TASK DEPENDENCIES) are expressed as
 * prerequisite titles here and resolved to real self-relation rows by
 * src/lib/roadmap/generate.ts after all 30 rows exist.
 */
export const TASK_TEMPLATES: TaskTemplateSeed[] = [
  // =====================================================================
  // PASSION
  // =====================================================================
  {
    stage: "PASSION",
    category: "Purpose",
    title: "Define Business Purpose",
    whyItMatters:
      "A clear purpose is what keeps your decisions consistent and keeps you motivated when things get hard — it's the foundation everything else in your Blueprint builds on.",
    thinkPrompt: "Before you write anything, think: if your business disappeared tomorrow, what would your customers actually miss?",
    instructions: [
      step("problem", "What problem are you solving?", "Describe the core problem your business exists to solve."),
      step("who", "Who does it affect?", "Who experiences this problem most acutely?"),
      step("why_you", "Why you?", "Why are you the right person or business to solve it?"),
    ],
    implementGuidance: "Keep this purpose statement somewhere visible — it should guide every offer, message, and decision you make next.",
    measurePrompt: "Revisit this every 6 months: does your day-to-day work still connect back to this purpose?",
    difficulty: "BEGINNER",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 15,
    blueprintDestination: "Purpose",
    prerequisiteTitles: [],
    order: 1,
  },
  {
    stage: "PASSION",
    category: "Mission",
    title: "Create Mission Statement",
    whyItMatters:
      "Your mission translates purpose into action — it's a working sentence you can use in your bio, pitch, and website today.",
    thinkPrompt: "Think about what you do, for whom, and how — in plain language, not corporate-speak.",
    instructions: [
      step("mission", "Write your mission statement", "In 1–2 sentences: what does your business do, for whom, and how?"),
    ],
    implementGuidance: "Put this mission statement in your website's About section and your social bios this week.",
    measurePrompt: "Ask a customer to repeat your mission back to you in their own words — does it land?",
    difficulty: "BEGINNER",
    impact: "MEDIUM",
    priority: "MUST_DO",
    estimatedMins: 15,
    blueprintDestination: "Mission",
    prerequisiteTitles: ["Define Business Purpose"],
    order: 2,
  },
  {
    stage: "PASSION",
    category: "Vision",
    title: "Create Vision Statement",
    whyItMatters: "A vision gives you something to build toward — without one, it's easy to react to whatever comes up instead of building toward something.",
    thinkPrompt: "Picture your business 3 years from now, running well. What does that actually look like?",
    instructions: [
      step("vision", "Write your 3-year vision", "Describe what your business looks like in 3 years if things go well."),
      step("why_matters", "Why does that matter to you?", "What would achieving this vision mean for you personally?"),
    ],
    implementGuidance: "Use this vision to evaluate new opportunities: does this move me toward it, or away?",
    measurePrompt: "Once a year, check: is this still the vision you're building toward, or has it evolved?",
    difficulty: "BEGINNER",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "Vision",
    prerequisiteTitles: ["Define Business Purpose"],
    order: 3,
  },
  {
    stage: "PASSION",
    category: "Ideal Customer",
    title: "Define Ideal Customer",
    whyItMatters: "Trying to serve everyone usually means your marketing, offer, and messaging resonate with no one — clarity here sharpens everything downstream.",
    thinkPrompt: "Think of your best customer so far. What made them a great fit?",
    instructions: [
      step("who", "Who are they?", "Describe your ideal customer — role, life stage, or business type."),
      step("situation", "What's their situation?", "What's going on in their life or business right before they need you?"),
      step("desired_outcome", "What do they want?", "What outcome are they actually trying to achieve?"),
    ],
    implementGuidance: "Write this description somewhere you'll see it while creating marketing content — it should shape your words and images.",
    measurePrompt: "After your next 5 sales, check: did your actual customers match this profile?",
    difficulty: "BEGINNER",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 20,
    blueprintDestination: "Ideal Customer",
    prerequisiteTitles: [],
    order: 4,
  },
  {
    stage: "PASSION",
    category: "Customer Pain Points",
    title: "Identify Customer Pain Points",
    whyItMatters: "If you can't name the problem precisely, your marketing and offer will stay generic — precision here is what makes messaging click.",
    thinkPrompt: "Think about the last 3 conversations you had with a prospect or customer. What frustration came up?",
    instructions: [
      step("top_pains", "Top 3 pain points", "List the 3 problems your ideal customer struggles with most."),
      step("current_solution", "What are they doing now?", "How are they dealing with this today, without you?"),
      step("cost_of_inaction", "What does it cost them?", "What happens if this problem stays unsolved?"),
    ],
    implementGuidance: "Use these exact pain points as headlines in your marketing — customers respond to their own words reflected back.",
    measurePrompt: "Every quarter, ask 3 customers what their biggest struggle was before working with you — does the list still hold?",
    difficulty: "BEGINNER",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 20,
    blueprintDestination: "Customer Pain Points",
    prerequisiteTitles: ["Define Ideal Customer"],
    order: 5,
  },
  {
    stage: "PASSION",
    category: "Business Overview",
    title: "Define Core Offer",
    whyItMatters: "A confusing offer is one of the most common reasons a good business struggles to sell — this is the heart of your Business Overview.",
    thinkPrompt: "Think about the transformation you deliver, not just the deliverable.",
    instructions: [
      step("what", "What are you selling?", "Describe your main product or service in plain terms.", "short_text"),
      step("for_whom", "Who is it for?", "Who is this specific offer built for?", "short_text"),
      step("problem_solved", "What problem does it solve?", "Connect the offer directly to the pain point it addresses."),
      step("result", "What result does the customer get?", "Describe the outcome, not just the process."),
      step("different", "What makes it different?", "What makes this offer different from the alternatives?"),
    ],
    implementGuidance: "This becomes the backbone of your website's homepage and your one-line pitch — reuse it everywhere.",
    measurePrompt: "When a stranger reads this, can they tell what you sell and who it's for in 5 seconds?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 25,
    blueprintDestination: "Business Overview",
    prerequisiteTitles: ["Identify Customer Pain Points"],
    order: 6,
  },
  {
    stage: "PASSION",
    category: "Elevator Pitch",
    title: "Create Elevator Pitch",
    whyItMatters: "If you can't explain your business in one breath, customers and referral partners can't either.",
    thinkPrompt: "Imagine you have 15 seconds in an elevator — what's the one thing you want them to remember?",
    instructions: [
      step("pitch", "Write your elevator pitch", "In 2–3 sentences you could say out loud: what you do, for whom, and the result they get."),
    ],
    implementGuidance: "Practice saying this out loud 3 times — it should sound natural, not memorized.",
    measurePrompt: "Say it to someone outside your industry — do they understand what you do without follow-up questions?",
    difficulty: "BEGINNER",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 15,
    blueprintDestination: "Elevator Pitch",
    prerequisiteTitles: ["Define Core Offer"],
    order: 7,
  },
  {
    stage: "PASSION",
    category: "Value Proposition",
    title: "Create Value Proposition",
    whyItMatters: "Without clear differentiation, price becomes the only thing customers can compare — a strong value proposition changes that conversation.",
    thinkPrompt: "Think about the one thing you do that competitors genuinely don't.",
    instructions: [
      step("differentiator", "What makes you different?", "What do you offer that alternatives don't?"),
      step("proof", "What's your proof?", "What evidence backs this up — results, experience, method?"),
    ],
    implementGuidance: "Feature this value proposition prominently on your pricing or services page.",
    measurePrompt: "When you lose a sale, ask why — does the answer relate to this value proposition?",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "Value Proposition",
    prerequisiteTitles: ["Define Core Offer"],
    order: 8,
  },
  {
    stage: "PASSION",
    category: "Business Goals",
    title: "Set 12-Month Goals",
    whyItMatters: "Vague goals produce vague effort — a specific goal makes it obvious what to prioritize this month.",
    thinkPrompt: "Think about what would make this year feel like a real success, not just \"busy.\"",
    instructions: [
      step("goal", "Your primary 12-month goal", "State one specific, measurable goal for the next 12 months."),
      step("why", "Why this goal?", "Why does this goal matter more than the alternatives right now?"),
    ],
    implementGuidance: "Break this into a 90-day goal — that's the first checkpoint on the way there.",
    measurePrompt: "Check progress against this goal monthly — is your day-to-day actually moving it forward?",
    difficulty: "BEGINNER",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 15,
    blueprintDestination: "Business Goals",
    prerequisiteTitles: ["Create Vision Statement"],
    order: 9,
  },

  // =====================================================================
  // POWER
  // =====================================================================
  {
    stage: "POWER",
    category: "Products & Services",
    title: "Finalize Products and Services",
    whyItMatters: "Loosely defined offers are hard to price, market, or deliver consistently — finalizing this unlocks pricing and marketing.",
    thinkPrompt: "Think about everything you currently sell — what's core, and what's a distraction?",
    instructions: [
      step("core_offers", "List your core products/services", "What do you sell today? Keep it to your real, active offers."),
      step("deliverables", "What's included in each?", "For your main offer, what exactly does the customer receive?"),
    ],
    implementGuidance: "Update your website and sales materials so they match this exact list — remove anything you no longer offer.",
    measurePrompt: "Every 6 months, review: is anything on this list no longer worth offering?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 25,
    blueprintDestination: "Products & Services",
    prerequisiteTitles: ["Define Core Offer"],
    order: 1,
  },
  {
    stage: "POWER",
    category: "Pricing",
    title: "Build Pricing Strategy",
    whyItMatters: "Without a pricing strategy, prices tend to drift down under pressure — a clear strategy protects your margins.",
    thinkPrompt: "Think about your costs, your time, and the value delivered — not just what competitors charge.",
    instructions: [
      step("current_pricing", "What do you charge today?", "List your current prices for your core offers."),
      step("basis", "How did you set these prices?", "Cost-based, value-based, competitor-based, or a guess?"),
      step("target_pricing", "What should you charge?", "Based on value delivered, what would a confident price be?"),
    ],
    implementGuidance: "Test a price increase on your next new customer before changing pricing for everyone.",
    measurePrompt: "Track your profit margin per sale quarterly — is pricing keeping pace with your costs?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 25,
    blueprintDestination: "Pricing",
    prerequisiteTitles: ["Finalize Products and Services"],
    order: 2,
  },
  {
    stage: "POWER",
    category: "Lead Generation",
    title: "Create Lead Generation Plan",
    whyItMatters: "Without a consistent lead-generation method, revenue can become unpredictable — one reliable channel changes that.",
    thinkPrompt: "Think about where your best customers have actually come from so far.",
    instructions: [
      step("primary_channel", "Your primary lead channel", "Which one channel will you commit to consistently?"),
      step("cadence", "How often will you show up there?", "What's a realistic, repeatable cadence?"),
      step("offer_hook", "What draws someone in?", "What's the hook that gets a stranger to pay attention?"),
    ],
    implementGuidance: "Block time on your calendar weekly for this one channel — consistency beats spreading thin across five.",
    measurePrompt: "Track new leads per week from this channel — is it trending up?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 30,
    blueprintDestination: "Lead Generation",
    prerequisiteTitles: ["Define Ideal Customer", "Define Core Offer", "Build Pricing Strategy"],
    order: 3,
  },
  {
    stage: "POWER",
    category: "Marketing",
    title: "Create Marketing Plan",
    whyItMatters: "Inconsistent marketing produces inconsistent revenue — a simple plan is what makes marketing sustainable.",
    thinkPrompt: "Think about what you can realistically sustain every week, not what looks impressive for one month.",
    instructions: [
      step("message", "Your core marketing message", "What's the one message you want repeated back to you?"),
      step("channels", "Where will you show up?", "Which 1–2 channels will carry this message?"),
      step("cadence", "How often?", "What's a sustainable posting/outreach cadence?"),
    ],
    implementGuidance: "Batch a month of content in one sitting so consistency doesn't depend on daily motivation.",
    measurePrompt: "Monthly, check: did you actually hit the cadence you planned?",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 25,
    blueprintDestination: "Marketing",
    prerequisiteTitles: ["Define Ideal Customer"],
    order: 4,
  },
  {
    stage: "POWER",
    category: "Sales Process",
    title: "Create Sales Process",
    whyItMatters: "Without a repeatable process, sales results depend entirely on memory and mood — writing it down makes it teachable and consistent.",
    thinkPrompt: "Think through your last 3 sales, step by step, from first contact to close.",
    instructions: [
      step("steps", "Your sales steps", "List the steps from first contact to closed sale."),
      step("objections", "Common objections", "What are the top 2–3 objections you hear, and how do you handle them?"),
    ],
    implementGuidance: "Turn this into a simple checklist you (or a future hire) can follow for every prospect.",
    measurePrompt: "Track your close rate — does it improve as you follow this process consistently?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 25,
    blueprintDestination: "Sales Process",
    prerequisiteTitles: ["Finalize Products and Services", "Build Pricing Strategy"],
    order: 5,
  },
  {
    stage: "POWER",
    category: "Follow-Up",
    title: "Create Follow-Up Process",
    whyItMatters: "Most sales are lost to silence, not rejection — a follow-up process recovers deals that would otherwise disappear.",
    thinkPrompt: "Think about the last prospect who went quiet — what would have kept the conversation alive?",
    instructions: [
      step("timing", "Follow-up timing", "How many days after first contact do you follow up, and how many times?"),
      step("method", "How will you follow up?", "Email, call, text — what's realistic for you to sustain?"),
    ],
    implementGuidance: "Set a recurring reminder or simple tracker so no prospect falls through the cracks.",
    measurePrompt: "Track how many \"lost\" deals get recovered by a follow-up — is it worth the effort?",
    difficulty: "BEGINNER",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 15,
    blueprintDestination: "Follow-Up",
    prerequisiteTitles: ["Create Sales Process"],
    order: 6,
  },
  {
    stage: "POWER",
    category: "Customer Journey",
    title: "Create Customer Journey",
    whyItMatters: "A weak first experience is one of the fastest ways to lose a customer you just won — mapping the journey fixes that.",
    thinkPrompt: "Think about the first week after someone buys — what do they actually experience?",
    instructions: [
      step("first_steps", "First 3 steps after purchase", "What happens in the first days after someone buys?"),
      step("touchpoints", "Key touchpoints", "Where else do you interact with them before, during, and after delivery?"),
    ],
    implementGuidance: "Write this journey down as a simple checklist your team (or future you) can follow every time.",
    measurePrompt: "Ask new customers what surprised them, positively or negatively, in their first week.",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 25,
    blueprintDestination: "Customer Journey",
    prerequisiteTitles: ["Create Sales Process"],
    order: 7,
  },
  {
    stage: "POWER",
    category: "CRM",
    title: "Choose CRM",
    whyItMatters: "Leads that aren't tracked are leads that get forgotten — even a simple system beats memory.",
    thinkPrompt: "Think about how you're tracking prospects today, if at all.",
    instructions: [
      step("choice", "Which CRM or system will you use?", "Name the tool (even a spreadsheet counts to start).", "short_text"),
      step("fields", "What will you track?", "What information matters most about each prospect?"),
    ],
    implementGuidance: "Migrate your current prospects into this system this week — don't let it start empty.",
    measurePrompt: "Monthly, check: are you actually logging every new lead here, or falling back to memory?",
    difficulty: "BEGINNER",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "CRM",
    prerequisiteTitles: [],
    order: 8,
  },
  {
    stage: "POWER",
    category: "Operations",
    title: "Create Onboarding Process",
    whyItMatters: "A defined onboarding process makes every new customer's first experience consistent, not dependent on your mood that day.",
    thinkPrompt: "Think about what a new customer needs to know or do in their first week.",
    instructions: [
      step("steps", "Onboarding steps", "List the steps a new customer goes through when they start."),
      step("owner", "Who's responsible?", "Who runs each step — you, a tool, or a future team member?"),
    ],
    implementGuidance: "Turn this into a welcome email or checklist you send automatically to every new customer.",
    measurePrompt: "Ask new customers to rate their onboarding — track it over time.",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "Operations",
    prerequisiteTitles: ["Create Customer Journey"],
    order: 9,
  },
  {
    stage: "POWER",
    category: "Revenue Goals",
    title: "Build Financial Goals",
    whyItMatters: "You can't make good decisions about a business whose numbers you don't track — financial goals turn vague hopes into a plan.",
    thinkPrompt: "Think about the revenue number that would actually change things for you this year.",
    instructions: [
      step("revenue_goal", "12-month revenue goal", "What's your target revenue for the next 12 months?", "short_text"),
      step("monthly_target", "Monthly target", "What monthly average does that require?", "short_text"),
      step("profit_target", "Profit goal", "What profit margin are you aiming to keep?", "short_text"),
    ],
    implementGuidance: "Break the monthly target down by offer — how many sales of what does it actually take?",
    measurePrompt: "Review actual vs. target revenue monthly — adjust the plan, not just the hope.",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 20,
    blueprintDestination: "Revenue Goals",
    prerequisiteTitles: ["Set 12-Month Goals"],
    order: 10,
  },
  {
    stage: "POWER",
    category: "SOPs",
    title: "Create First SOP",
    whyItMatters: "Undocumented processes live only in your head, which makes delegation and scaling nearly impossible — one written SOP is the start.",
    thinkPrompt: "Think about the task you personally repeat most often.",
    instructions: [
      step("process_name", "Which process?", "Name the single most-repeated task you'll document.", "short_text"),
      step("steps", "Step-by-step", "Write out the steps in order, in enough detail someone else could follow them."),
    ],
    implementGuidance: "Hand this SOP to someone else (or re-read it cold) to check it's actually followable without you.",
    measurePrompt: "Next time you do this task, check: does the SOP still match reality?",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 30,
    blueprintDestination: "SOPs",
    prerequisiteTitles: ["Create Onboarding Process"],
    order: 11,
  },
  {
    stage: "POWER",
    category: "Automation",
    title: "Identify Automation Opportunities",
    whyItMatters: "Manual repetition is the ceiling on how much you can grow without burning out — automation raises that ceiling.",
    thinkPrompt: "Think about what you do manually every single week that a tool could do instead.",
    instructions: [
      step("candidates", "What could be automated?", "List 2–3 repetitive tasks that are good automation candidates."),
      step("first_pick", "Which one first?", "Which one will you automate first, and with what tool?"),
    ],
    implementGuidance: "Automate just the first one this month — don't try to automate everything at once.",
    measurePrompt: "Track hours saved per week after automating — was it worth the setup time?",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "BONUS",
    estimatedMins: 20,
    blueprintDestination: "Automation",
    prerequisiteTitles: ["Create First SOP"],
    order: 12,
  },

  // =====================================================================
  // LEGACY
  // =====================================================================
  {
    stage: "LEGACY",
    category: "Delegation",
    title: "Delegation Plan",
    whyItMatters: "Growth is capped by how much you personally can do — delegating even one task raises that ceiling.",
    thinkPrompt: "Think about the task you dread most that isn't actually the best use of your time.",
    instructions: [
      step("tasks_to_delegate", "What could you delegate?", "List 2–3 tasks that don't require you specifically."),
      step("first_step", "First delegation step", "Who could take on the first one, and when will you hand it off?"),
    ],
    implementGuidance: "Delegate the first task within 2 weeks, even if it feels easier to just do it yourself.",
    measurePrompt: "Track hours per week freed up as you delegate — is it going toward higher-value work?",
    difficulty: "INTERMEDIATE",
    impact: "HIGH",
    priority: "MUST_DO",
    estimatedMins: 20,
    blueprintDestination: "Delegation",
    prerequisiteTitles: ["Create First SOP"],
    order: 1,
  },
  {
    stage: "LEGACY",
    category: "Team",
    title: "Team Roles",
    whyItMatters: "Knowing which roles you need — before you're overwhelmed — means hiring becomes planned instead of reactive and expensive.",
    thinkPrompt: "Think about what only you can do versus what anyone with the right skill could do.",
    instructions: [
      step("roles_needed", "Roles you'll eventually need", "List the roles that would most free up your time or grow the business."),
      step("priority_role", "Which role first?", "Which role would have the biggest impact if filled first?"),
    ],
    implementGuidance: "Write a one-paragraph description of the priority role — even before you're ready to hire.",
    measurePrompt: "Revisit this list every 6 months as the business changes.",
    difficulty: "INTERMEDIATE",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "Team",
    prerequisiteTitles: ["Delegation Plan"],
    order: 2,
  },
  {
    stage: "LEGACY",
    category: "Hiring",
    title: "Hiring Roadmap",
    whyItMatters: "A hiring roadmap turns \"someday I'll need help\" into a plan with a timeline.",
    thinkPrompt: "Think about what revenue or workload milestone would trigger your next hire.",
    instructions: [
      step("trigger", "What triggers your next hire?", "What milestone (revenue, workload) means it's time?", "short_text"),
      step("first_hire", "Your first hire", "What role, and full-time, part-time, or contractor?"),
    ],
    implementGuidance: "Draft a simple job description now, even months before you plan to hire — it clarifies your own thinking.",
    measurePrompt: "Check quarterly: have you hit the trigger point you defined?",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 25,
    blueprintDestination: "Hiring",
    prerequisiteTitles: ["Team Roles"],
    order: 3,
  },
  {
    stage: "LEGACY",
    category: "Scaling Strategy",
    title: "Scaling Strategy",
    whyItMatters: "Revenue that only grows by adding more of your own hours doesn't scale — this task looks for growth that doesn't require more of you.",
    thinkPrompt: "Think about where you could increase output without proportionally increasing your own hours.",
    instructions: [
      step("lever", "Your scaling lever", "What's one way to grow revenue without growing your hours at the same rate?"),
      step("blocker", "What's in the way?", "What needs to be true first for this to work?"),
    ],
    implementGuidance: "Pick the single biggest blocker and make it this quarter's focus.",
    measurePrompt: "Track revenue per hour worked over time — is it trending up?",
    difficulty: "ADVANCED",
    impact: "HIGH",
    priority: "SHOULD_DO",
    estimatedMins: 25,
    blueprintDestination: "Scaling Strategy",
    prerequisiteTitles: ["Build Financial Goals", "Identify Automation Opportunities"],
    order: 4,
  },
  {
    stage: "LEGACY",
    category: "Recurring Revenue",
    title: "Recurring Revenue Strategy",
    whyItMatters: "A single one-time-sale revenue source is a single point of failure — recurring revenue smooths out the ups and downs.",
    thinkPrompt: "Think about what you offer that a customer would want again and again.",
    instructions: [
      step("recurring_idea", "A recurring revenue idea", "What could you offer on a subscription, retainer, or membership basis?"),
      step("fit", "Does it fit your customer?", "Would your ideal customer actually want this ongoing?"),
    ],
    implementGuidance: "Pilot this with your 2–3 best existing customers before rolling it out broadly.",
    measurePrompt: "Track % of revenue that's recurring over time — is it growing?",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 20,
    blueprintDestination: "Recurring Revenue",
    prerequisiteTitles: ["Build Pricing Strategy"],
    order: 5,
  },
  {
    stage: "LEGACY",
    category: "Intellectual Property",
    title: "Intellectual Property Plan",
    whyItMatters: "Packaged assets — courses, templates, licenses — create value independent of your hours, and are worth protecting and developing deliberately.",
    thinkPrompt: "Think about what you already know or do well that could become a standalone asset.",
    instructions: [
      step("asset_idea", "A potential asset", "What could you turn into a course, template, book, or licensable process?"),
      step("protection", "Does it need protection?", "Does this need a trademark, copyright, or other protection?"),
    ],
    implementGuidance: "Start small — turn one existing process into a simple, sellable template first.",
    measurePrompt: "Track revenue or leads generated from this asset once it exists.",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "BONUS",
    estimatedMins: 25,
    blueprintDestination: "Intellectual Property",
    prerequisiteTitles: ["Define Core Offer"],
    order: 6,
  },
  {
    stage: "LEGACY",
    category: "Partnerships",
    title: "Strategic Partnership Plan",
    whyItMatters: "The right partnerships extend your reach further than you can alone — this plan makes that intentional instead of accidental.",
    thinkPrompt: "Think about businesses that already serve your ideal customer, without competing with you.",
    instructions: [
      step("partner_type", "What kind of partner?", "What type of business would complement yours?"),
      step("first_outreach", "Who first?", "Is there a specific business you could reach out to?"),
    ],
    implementGuidance: "Reach out to one potential partner this month with a specific, low-commitment idea.",
    measurePrompt: "Track leads or revenue that come through partnerships over time.",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "BONUS",
    estimatedMins: 20,
    blueprintDestination: "Partnerships",
    prerequisiteTitles: ["Scaling Strategy"],
    order: 7,
  },
  {
    stage: "LEGACY",
    category: "Succession",
    title: "Succession Strategy",
    whyItMatters: "Without a succession or exit plan, the business's value is trapped with you — even a rough plan changes how you build.",
    thinkPrompt: "Think about what you'd want to happen to this business in 10 years.",
    instructions: [
      step("long_term", "10-year outlook", "Sell it, pass it on, keep running it, or something else?", "short_text"),
      step("what_needed", "What needs to be true?", "What would need to exist for that outcome to be possible?"),
    ],
    implementGuidance: "Even a one-paragraph outline is enough to start — refine it as the business matures.",
    measurePrompt: "Revisit this plan yearly as your goals and the business evolve.",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "SHOULD_DO",
    estimatedMins: 25,
    blueprintDestination: "Succession",
    prerequisiteTitles: ["Hiring Roadmap"],
    order: 8,
  },
  {
    stage: "LEGACY",
    category: "Legacy Plan",
    title: "Legacy Impact Plan",
    whyItMatters: "A business run only for monthly income rarely becomes a lasting asset — this plan connects your work to impact beyond revenue.",
    thinkPrompt: "Think about the impact you want this business to have beyond your own income.",
    instructions: [
      step("impact", "What impact do you want?", "Beyond income, what impact do you want your business to have?"),
      step("legacy_summary", "Your legacy, in one paragraph", "Pulling it all together — what do you want this business to be remembered for?"),
    ],
    implementGuidance: "Share this with your facilitator or a trusted advisor — outside perspective sharpens a legacy plan.",
    measurePrompt: "Revisit this yearly, alongside your succession strategy.",
    difficulty: "ADVANCED",
    impact: "MEDIUM",
    priority: "BONUS",
    estimatedMins: 20,
    blueprintDestination: "Legacy Plan",
    prerequisiteTitles: ["Succession Strategy"],
    order: 9,
  },
];
